---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Update and upgrade
      apt:
        update_cache: yes
    - name: Install essential packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
    - name: Add an Apt signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add an Apt repository
      apt_repository:
        repo: "deb [arch=amd64] http://download.docker.com/linux/ubuntu focal stable"
        state: present
    - name: Update and upgrade
      apt:
        update_cache: yes
    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

