---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install essential packages
      apt:
        name:
          - vim
          - git
          - fcitx-mozc
          - xsel
        state: latest

